[package]
name = "bloomable"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
ethcore-bigint = { path = "../bigint" }

[dev-dependencies]
keccak-hash = { path = "../hash" }
