[package]
name = "parity-machine"
version = "0.1.0"
description = "Generalization of a state machine for consensus engines"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore-util = { path = "../util" }
ethcore-bigint = { path = "../util/bigint" }
