[package]
name = "native-contracts"
description = "Generated Rust code for Ethereum contract ABIs"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[dependencies]
ethabi = "4.0"
futures = "0.1"
byteorder = "1.0"
ethcore-bigint = { path = "../../util/bigint" }

[build-dependencies]
native-contract-generator = { path = "generator" }

[features]
default = []
test_contracts = []
